version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ossyne_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ossyne_db_data:/var/lib/mysql

volumes:
  ossyne_db_data: